# Generated by Django 5.1 on 2024-09-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iabData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicacao',
            name='mov_avisar_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='indicacao',
            name='mov_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicacao',
            name='mov_data_agenda',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicacao',
            name='mov_descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicacao',
            name='mov_tipo',
            field=models.CharField(choices=[('CONCLUSAO_PARECER', 'Conclusão do Parecer'), ('DECISAO_PLENARIO', 'Decisão do Plenário'), ('PARECER', 'Parecer'), ('PAUTA', 'Pauta'), ('RECEBIMENTO', 'Recebimento'), ('REMESSA', 'REMESSA')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='indicacao',
            name='materia',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='indicacao',
            name='objeto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='indicacao',
            name='relator',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='indicacao',
            name='status',
            field=models.CharField(choices=[('AD_REFEREDUM', 'Ad Referendum'), ('AG_NOVO_AGENDAMENTO', 'Aguardando novo agendamento'), ('AGENDADO_PARA_SESSAO_ORDINARIA', 'Agendado para Sessão Ordinária'), ('APENSADA_A_INDICACAO_N032024', 'Apensada à indicação nº 03/2024'), ('APENSADA_A_INDICACAO_N442023', 'Apensada à indicação nº 44/2023'), ('APROVADO', 'Aprovado'), ('APROVADO_MAIORIA', 'Aprovado pela maioria'), ('APROVADO_COMISSAO_AGUARD_PLENARIO', 'Aprovado na Comissão - Aguardando pauta em plenário'), ('APROVADO_PARCIALMENTE', 'Aprovado parcialmente'), ('APROVADO_UNANIMAMENTE', 'Aprovado unanimamente'), ('ARQUIVADO', 'Arquivado'), ('ATIVO', 'Ativo'), ('ENTREGUE_POR_UMA_COMISSAO', 'Entregue por uma comissão - Aguardando as demais'), ('NA_COMISSAO_PARA_ ELABORACAO_DE_PARECER', 'Nas Comissões para elaboração de parecer'), ('PARECER_ENTREGUE_AG_VOTACAO', 'Parecer entregue - Aguardando votação na Comissão'), ('PERDA_DE_OBJETO', 'Perda de Objeto'), ('REJEITADO', 'Rejeitado'), ('REJEITDO_MAIORIA', 'Rejeitado pela maioria'), ('REJEITADO_UNANIMAMENTE', 'Rejeitado Unanimamente'), ('SOBRESTADO', 'Sobrestado')], max_length=100),
        ),
        migrations.AlterField(
            model_name='indicacao',
            name='tag',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mandato',
            name='posse',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
